### PR TITLE
Fills timestamps before publishing frames

### PR DESCRIPTION
**Pull request by tcsantini**
For frames in which there were no EOF but a change in the frame ID, the
timestamp was not being filled.

Please note I have just applied this one and will be testing during the next days.

### CODE REVIEW

**Comment by pointcontrols** [comment]
@tcsantini On what device have you observed this behaviour?

**Comment by tcsantini** [comment]
On a device that I can't disclose (NDA) and, more pertinent to you guys, three distinct Pupil Cam1.

**Comment by pointcontrols** [comment]
Thanks, regaeding pupil cams, does it occur sporadic or you have found a
way to trigger it?

**Comment by tcsantini** [comment]
No particular trigger that I know of, but it's not uncommon for it to happen.

**Pull request merged**
